name: CI/CD production
env:
  BUILD_NAME: flaresolverr
on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:

  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - name: Set variables useful for later
        id: useful_vars
        run: |-
          echo "::set-output name=timestamp::$(date +%s)"
          echo "::set-output name=short_sha::${GITHUB_SHA::8}"

      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
 
      - name: Build and push the Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: ${{ github.ref == 'refs/heads/master'}}
          tags: |
            ghcr.io/arkptz/${{ env.BUILD_NAME }}:latest
            ghcr.io/arkptz/${{ env.BUILD_NAME }}:${{ github.ref_name }}-${{ steps.useful_vars.outputs.short_sha }}-${{ steps.useful_vars.outputs.timestamp }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          # no-cache: true
        